### ISSUE TITLE
Production build fails if compatibilityVersion: 4 is enabled

### ISSUE THREAD

**Issue by SqrTT** [dulnan/nuxt-multi-cache#74]
Example of `nuxt.config.ts`
```typescript
export default defineNuxtConfig({
  modules: ['nuxt-multi-cache'],
  multiCache: {
    route: { enabled: true },
  },
  future: {
    compatibilityVersion: 4
  }
})
```
`package.json`

```json
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "typecheck": "nuxt typecheck",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "nuxt": "^3.13.1",
    "nuxt-multi-cache": "^3.3.3"
  }
}
```

after `npm run build`

causes error to show up:
```
<snip>
✔ Server built in 354ms                                                                                                                             7:22:38 PM
✔ Generated public .output/public                                                                                                             nitro 7:22:38 PM
ℹ Building Nuxt Nitro server (preset: node-server)                                                                                            nitro 7:22:38 PM
[plugin inject] node_modules/.cache/nuxt/.nuxt/multiCache.serverOptions.ts: rollup-plugin-inject: failed to parse /Users/anatolii/git/playbround/nuxt-app/node_modules/.cache/nuxt/.nuxt/multiCache.serverOptions.ts. Consider restricting the plugin to particular files via options.include


[nitro 7:22:38 PM]  ERROR  RollupError: node_modules/.cache/nuxt/.nuxt/multiCache.serverOptions.ts (2:12): Expected ',', got '{' (Note that you need plugins to import files that are not JavaScript)


1: 
2: import type { MultiCacheServerOptions } from '../../../nuxt-multi-cache/dist/runtime/types.ts'
               ^
3: const serverOptions: MultiCacheServerOptions = {}


[7:22:38 PM]  ERROR  node_modules/.cache/nuxt/.nuxt/multiCache.serverOptions.ts (2:12): Expected ',', got '{' (Note that you need plugins to import files that are not JavaScript)

  at getRollupError (node_modules/rollup/dist/es/shared/parseAst.js:392:41)
  at ParseError.initialise (node_modules/rollup/dist/es/shared/node-entry.js:11485:28)
  at convertNode (node_modules/rollup/dist/es/shared/node-entry.js:13181:10)
  at convertProgram (node_modules/rollup/dist/es/shared/node-entry.js:12525:12)
  at Module.setSource (node_modules/rollup/dist/es/shared/node-entry.js:14346:24)
  at async ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/node-entry.js:19003:13) 



[7:22:38 PM]  ERROR  node_modules/.cache/nuxt/.nuxt/multiCache.serverOptions.ts (2:12): Expected ',', got '{' (Note that you need plugins to import files that are not JavaScript)
```

It's started to happen in `3.3.0` and working fine in `3.2.0`

**Comment by dulnan** [comment]
Short update: I had opened an issue in the Nuxt repository because I was under the impression that it's a bug in Nuxt. However I will now try to find a workaround here to make it work when setting `compatibilityVersion: 4`.

**Comment by dulnan** [comment]
The upcoming release (3.4.0) will add support for using the module with `compatibilityVersion: 4`. If a server options file is used, it can still remain in `<rootDir>/app/multiCache.serverOptions.ts`, however, putting it in `<rootDir>/multiCache.serverOptions.ts` also works and will become the new default.

**Comment by SqrTT** [comment]
@dulnan  Thank you!
