### ISSUE TITLE
Error on nuxt build

### ISSUE THREAD

**Issue by thunder87** [dulnan/nuxt-multi-cache#80]
Everything works as expected using `nuxt dev`

Nuxt config 
````
  compatibilityDate: '2024-11-01',
  future: {
    compatibilityVersion: 4,
  },
  experimental: {
    sharedPrerenderData: true,
    payloadExtraction: true,
    inlineRouteRules: true,
    asyncContext: true,
  },
  multiCache: {
    data: {
      enabled: true,
    },
  },
````

Build error
```` ℹ Building Nuxt Nitro server (preset: node-server, compatibility date: 2024-11-01)                                                                                                                     
[plugin inject] node_modules/.cache/nuxt/.nuxt/multiCache.serverOptions.ts: rollup-plugin-inject: failed to parse /Users/xxxxx/site/node_modules/.cache/nuxt/.nuxt/multiCache.serverOptions.ts. Consider restricting the plugin to particular files via options.include

ERROR  RollupError: node_modules/.cache/nuxt/.nuxt/multiCache.serverOptions.ts (2:12): Expected ',', got '{' (Note that you need plugins to import files that are not JavaScript)

import type { MultiCacheServerOptions } from '../../../nuxt-multi-cache/dist/runtime/types.ts'
               ^
const serverOptions: MultiCacheServerOptions = {}


ERROR  node_modules/.cache/nuxt/.nuxt/multiCache.serverOptions.ts (2:12): Expected ',', got '{' (Note that you need plugins to import files that are not JavaScript)

at getRollupError (node_modules/rollup/dist/es/shared/parseAst.js:396:41)
at ParseError.initialise (node_modules/rollup/dist/es/shared/node-entry.js:13281:28)
at convertNode (node_modules/rollup/dist/es/shared/node-entry.js:14992:10)
at convertProgram (node_modules/rollup/dist/es/shared/node-entry.js:14235:12)
at Module.setSource (node_modules/rollup/dist/es/shared/node-entry.js:15978:24)
at async ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/node-entry.js:19874:13)


ERROR  node_modules/.cache/nuxt/.nuxt/multiCache.serverOptions.ts (2:12): Expected ',', got '{' (Note that you need plugins to import files that are not JavaScript)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````

**Comment by dulnan** [comment]
This will be fixed in the upcoming release
